import {
  Compass, Cpu, WandSparkles, Gauge, Flower2, Globe2, Bug, Backpack, Utensils, Archive, TramFront, Wrench, Library, Cog, Building2, UserRound, UserRoundPlus, Sprout, Fish, Armchair, MessagesSquare, CalendarDays, Puzzle, Shirt, Hammer, Volume2, Terminal, ContactRound, PawPrint, Map, PanelsTopLeft, Shield, Swords, Clapperboard, FlaskConical, ScrollText, Orbit, TrendingUp, Megaphone, EyeOff, ScanFace, Image, BugOff, Moon, DoorOpen, Ghost, Package, Sparkles, Smile, BoomBox, CloudSun, TriangleAlert, Car, SlidersHorizontal, Languages, PersonStanding, Zap, Gem, Gamepad2, Flag, Boxes, Sunrise, Footprints, Trophy, Scan, Music, RefreshCw, Fingerprint, UsersRound, Scale, Blocks, Save, LayoutGrid, MapPinned, Cuboid, TreePine, Route, Trees, House, Store, Factory, BriefcaseBusiness, Rabbit, Palette, MapPin, Shapes, FileCode2, Dices, Tent, Castle, Bot, Crosshair, Watch, BrickWall, Radio, FlagTriangleRight, ShieldHalf,
  type LucideIcon,
} from 'lucide-react';

// Exact semantic labels from the category catalog, independent of the UI language.
// Reuse an SVG only for categories with the same meaning across providers.
export const CATEGORY_ICONS: Readonly<Record<string, LucideIcon>> = {
  "adventure": Compass,
  "adventure worlds": Compass,
  "technology": Cpu,
  "magic": WandSparkles,
  "optimization": Gauge,
  "performance": Gauge,
  "decoration": Flower2,
  "world generation": Globe2,
  "mobs": Bug,
  "equipment": Backpack,
  "gear": Backpack,
  "food": Utensils,
  "storage": Archive,
  "transportation": TramFront,
  "transport": TramFront,
  "utility": Wrench,
  "utilities": Wrench,
  "qol": Wrench,
  "tweaks & quality of life": Wrench,
  "library": Library,
  "game mechanics": Cog,
  "gameplay mechanics": Cog,
  "buildings": Building2,
  "building": Building2,
  "characters": UserRound,
  "character": UserRound,
  "npcs": UserRound,
  "new characters": UserRoundPlus,
  "crops": Sprout,
  "farming": Sprout,
  "fishing": Fish,
  "furniture": Armchair,
  "dialogue": MessagesSquare,
  "events": CalendarDays,
  "expansions": Puzzle,
  "mod": Puzzle,
  "from terraria mods": Puzzle,
  "clothing": Shirt,
  "suits": Shirt,
  "crafting": Hammer,
  "audio": Volume2,
  "cheats": Terminal,
  "portraits": ContactRound,
  "pets / horses": PawPrint,
  "livestock and animals": PawPrint,
  "animals": PawPrint,
  "pet": PawPrint,
  "maps": Map,
  "map": Map,
  "user interface": PanelsTopLeft,
  "interface": PanelsTopLeft,
  "armour": Shield,
  "armor": Shield,
  "clothing/armor": Shield,
  "armour and clothing": Shield,
  "weapons": Swords,
  "pvp": Swords,
  "animation": Clapperboard,
  "animations": Clapperboard,
  "alchemy": FlaskConical,
  "quests and adventures": ScrollText,
  "scenario": ScrollText,
  "races, classes, and birthsigns": Orbit,
  "skills and leveling": TrendingUp,
  "shouts": Megaphone,
  "stealth": EyeOff,
  "body, face, and hair": ScanFace,
  "appearance": ScanFace,
  "character customisation": ScanFace,
  "visuals and graphics": Image,
  "bug fixes": BugOff,
  "moons": Moon,
  "interiors": DoorOpen,
  "monsters": Ghost,
  "enemies": Ghost,
  "items": Package,
  "item": Package,
  "cosmetics": Sparkles,
  "skins": Sparkles,
  "emotes": Smile,
  "boombox music": BoomBox,
  "weather": CloudSun,
  "weather and lighting": CloudSun,
  "hazards": TriangleAlert,
  "vehicles": Car,
  "vehicle": Car,
  "tweaks": SlidersHorizontal,
  "tweak": SlidersHorizontal,
  "language": Languages,
  "translation": Languages,
  "language/translations": Languages,
  "language/translation": Languages,
  "player characters": PersonStanding,
  "skills": Zap,
  "artifacts": Gem,
  "accessories": Gem,
  "gamemodes": Gamepad2,
  "gameplay": Gamepad2,
  "golf worlds": Flag,
  "all items worlds": Boxes,
  "starter worlds": Sunrise,
  "journey worlds": Footprints,
  "challenge worlds": Trophy,
  "high resolution": Scan,
  "music": Music,
  "overhaul": RefreshCw,
  "traits": Fingerprint,
  "perks": Fingerprint,
  "multiplayer": UsersRound,
  "companions": UsersRound,
  "balance": Scale,
  "framework": Blocks,
  "savegame": Save,
  "district style": LayoutGrid,
  "map theme": MapPinned,
  "prop": Cuboid,
  "tree": TreePine,
  "intersection": Route,
  "park": Trees,
  "environment": Trees,
  "residential": House,
  "commercial": Store,
  "industrial": Factory,
  "office": BriefcaseBusiness,
  "classes": BriefcaseBusiness,
  "creature": Rabbit,
  "creatures": Rabbit,
  "art": Palette,
  "locations": MapPin,
  "props and decorations": Shapes,
  "scripts": FileCode2,
  "dice": Dices,
  "player settlement": Tent,
  "sim settlements 2": Castle,
  "power armour": Bot,
  "ammo": Crosshair,
  "pip-boy": Watch,
  "crafting - home/settlement": BrickWall,
  "radio": Radio,
  "factions": FlagTriangleRight,
  "weapons and armour": ShieldHalf,
};

export const categoryIcon = (label: string): LucideIcon => CATEGORY_ICONS[label.toLowerCase()] ?? Puzzle;
